Use bump2version (#9)
* Use bump2version

* Remove unused import

* Comment out unused variables

* Remove unused param: sigfig from argument

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Use scikit-learn

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/.github/workflows/pypi-publish.yml b/.github/workflows/pypi-publish.yml
--- a/.github/workflows/pypi-publish.yml
+++ b/.github/workflows/pypi-publish.yml
@@ -8,19 +8,41 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.8
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install setuptools wheel twine
-    - name: Build and publish
-      env:
-        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
-        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
-      run: |
-        python setup.py sdist bdist_wheel
-        twine upload dist/*
+      - uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
+      - name: Extract the tag
+        id: vars
+        run: |
+          echo "::set-output name=tag::${GITHUB_REF##*/}"
+      - name: Check tag validity
+        env:
+          VERSION: ${{ steps.vars.outputs.tag }}
+        run: |
+          grep "^v[[:digit:]]\.[[:digit:]]\.[[:digit:]]$" <<< "$VERSION" || (echo "Invalid version: '$VERSION'" && exit 42)
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install setuptools wheel twine bump2version
+      - name: Bump the version
+        env:
+          VERSION: ${{ steps.vars.outputs.tag }}
+        run: |
+          bump2version patch --no-commit --no-tag --verbose --new-version "${VERSION/v/}"
+      - name: Commit version bump
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          file_pattern: setup.py hillfit/__init__.py .bumpversion.cfg
+          commit_user_name: CI
+          commit_message: ${{ format('[auto][ci skip] Release {0}', steps.vars.outputs.tag) }}
+          tagging_message: ${{ steps.vars.outputs.tag }}
+          skip_dirty_check: false
+      - name: Build and publish
+        env:
+          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
+          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
+        run: |
+          python setup.py sdist bdist_wheel
+          twine upload dist/*
